---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  backendType: secretsManager
  region: us-west-2
  dataFrom:
    - mediawiki/mariadb

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: sumeshknayi/mediawiki
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE
              value: mediawiki
            - name: MYSQL_USER
              value: wiki
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD  
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_PASSWORD  
            - name: MYSQL_SERVER
              value: {{MYSQL_CLUSTER_HOSTNAME}}                                                 
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: mediawiki
            - name: MYSQL_USER
              value: wiki
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD  
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_PASSWORD                   

          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql    
      volumes:
         - name: mariadb-persistent-storage
           persistentVolumeClaim:
            claimName: mariadb-pvc       
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: mariadb
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  sessionAffinity: None
  type: ClusterIP
 ---
 apiVersion: v1
kind: Service
metadata:
  annotations:
    generated: by 8gwifi.org
  name: mediawiki
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mediawiki
  sessionAffinity: ClientIP
  type: LoadBalancer
 --
 apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    name: mediawiki-deployment-hpa
  spec:
    scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediawiki-deployment
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50